name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: debian-11-v4

    steps:
    - uses: actions/checkout@v3
    - name: Build the Stardew Container image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
